version: '3.8'

services:
  rag-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_CSE_ID=${GOOGLE_CSE_ID}
      - WEAVIATE_TRAFFIC_URL=${WEAVIATE_TRAFFIC_URL}
      - WEAVIATE_TRAFFIC_KEY=${WEAVIATE_TRAFFIC_KEY}
    volumes:
      - ./logs:/app/log
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s