services:
  ollama-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ollama-server
    networks:
      - my-net
    ports:
      - "11434:11434"
    command: ["sh","/pull-model.sh"]
    container_name: ollama-server

networks:
  my-net:
    driver: bridge
    
